### ISSUE TITLE
in mobile link bar is not coming

### ISSUE THREAD

**Issue by uttamjaiswal86** [pozh/Initio#1]
Hi,
First of all thanks for your help on responsive bootstrap website.When i see your this website then menu bar is not appearing on it.even in medium screen mobile that is also not coming.

**Comment by pixonte** [comment]
Thanks for letting me know about the issue, will update the template asap

**Comment by gustavomwk** [comment]
Hi, pozh Thanks for the work done

I issued a patch for this bug
please kindly accept the patch.

**Comment by pixonte** [comment]
thanks for the patch, applied. Also, I've just corrected the colors on that toggler, check out the most recent commit.
